version: '3.6'
services:

  unbound:
    image: klutchell/unbound
    container_name: unbound
    hostname: unbound
    restart: unless-stopped
    volumes:
      - ./volumes/unbound/config/:/opt/unbound/etc/unbound
    networks:
      pihole_net:
        ipv4_address: 172.21.0.3

# https://hub.docker.com/r/pihole/pihole
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless-stopped
    depends_on:
      - unbound
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8089:80/tcp"
    environment:
      - TZ=America/New_York
      - WEBPASSWORD=pihole
      - DNS1=172.21.0.3
      - DNS2=no
      - REV_SERVER=true
      - REV_SERVER_TARGET=192.168.0.1
      - REV_SERVER_DOMAIN=local
      - REV_SERVER_CIDR=192.168.0.0/24
      - DNS_FQDN_REQUIRED=false
      - DNS_BOGUS_PRIV=false
      - DNSSEC=false
      - INTERFACE=eth0
      - DNSMASQ_LISTENING=local
    volumes:
      - ./volumes/pihole/etc-pihole/:/etc/pihole/
      - ./volumes/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
# https://www.reddit.com/r/pihole/comments/kyme7b/help_pihole_up_failed_iproute2_and_iproute/gjjq5tf/
#    dns:
#      - 127.0.0.1
    cap_add:
      - NET_ADMIN
    networks:
      pihole_net:
        ipv4_address: 172.21.0.2

# ------------------------------------------------------------------------------------------------------------------------

networks:

  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

# ------------------------------------------------------------------------------------------------------------------------
